#!/bin/sh
#
# underscore(_.each) -> lodash(_.forEach)
#
cd $1 &&
grasp --equery '_.each($collection, $function, $context)' \
    --replace '_.forEach({{collection}}, _.bind({{function}}, {{context}}))' \
    --in-place --only-matching --recursive . > /dev/null &&
git commit -a -m 'underscore(_.each) -> lodash(_.forEach)' > /dev/null
