#!/bin/sh
#
# $ ./lodash3_to_lodash4 directory_with_js_to_refactor
#
# All JS is refactored: you must remove `node_modules` beforehand.
#
DIRECTORY=`readlink -f $1`
if [ ! -d $DIRECTORY ] || [ -z $DIRECTORY ]; then
  echo "Single directory is mandatory"
  exit 1
fi

echo 'lodash(_.find) -> lodash(_.find)'
(
  grasp --equery '_.find($object, $key, $value)' --replace '_.find({{object}}, [{{key}}, {{value}}])' \
    --in-place --only-matching --recursive $DIRECTORY ||
  echo "$(tput setaf 3)Bad stuff with lodash(_.find) -> lodash(_.find)$(tput setaf 0)"
) &&
cd $DIRECTORY > /dev/null &&
git commit -a -m 'lodash(_.find) -> lodash(_.find)' > /dev/null &&
cd - > /dev/null

echo 'lodash(_.padLeft) -> lodash(_.padStart)'
(
  grasp --equery '_.padLeft($string, $length)' --replace '_.padStart({{string}}, {{length}})' \
    --in-place --only-matching --recursive $DIRECTORY ||
  echo "$(tput setaf 3)Bad stuff with lodash(_.padLeft) -> lodash(_.padStart)$(tput setaf 0)"
) &&
cd $DIRECTORY > /dev/null &&
git commit -a -m 'lodash(_.padLeft) -> lodash(_.padStart)' > /dev/null &&
cd - > /dev/null

echo 'lodash(_.padLeft) -> lodash(_.padStart)'
(
  grasp --equery '_.padLeft($string, $length, $chars)' --replace '_.padStart({{string}}, {{length}}, {{chars}})' \
    --in-place --only-matching --recursive $DIRECTORY ||
  echo "$(tput setaf 3)Bad stuff with lodash(_.padLeft) -> lodash(_.padStart)$(tput setaf 0)"
) &&
cd $DIRECTORY > /dev/null &&
git commit -a -m 'lodash(_.padLeft) -> lodash(_.padStart)' > /dev/null &&
cd - > /dev/null

echo 'lodash(_.padRight) -> lodash(_.padEnd)'
(
  grasp --equery '_.padRight($string, $length)' --replace '_.padEnd({{string}}, {{length}})' \
    --in-place --only-matching --recursive $DIRECTORY ||
  echo "$(tput setaf 3)Bad stuff with lodash(_.padRight) -> lodash(_.padEnd)$(tput setaf 0)"
) &&
cd $DIRECTORY > /dev/null &&
git commit -a -m 'lodash(_.padRight) -> lodash(_.padEnd)' > /dev/null &&
cd - > /dev/null

echo 'lodash(_.findWhere) -> lodash(_.find)'
(
  grasp --equery '_.findWhere($collection, $source)' --replace '_.find({{collection}}, {{source}})' \
    --in-place --only-matching --recursive $DIRECTORY ||
  echo "$(tput setaf 3)Bad stuff with lodash(_.findWhere) -> lodash(_.find)$(tput setaf 0)"
) &&
cd $DIRECTORY > /dev/null &&
git commit -a -m 'lodash(_.findWhere) -> lodash(_.find)' > /dev/null &&
cd - > /dev/null

echo 'lodash(_.capitalize) -> lodash(_.upperFirst)'
(
  grasp --equery '_.capitalize($string)' --replace '_.upperFirst({{string}})' \
    --in-place --only-matching --recursive $DIRECTORY ||
  echo "$(tput setaf 3)Bad stuff with lodash(_.capitalize) -> lodash(_.upperFirst)$(tput setaf 0)"
) &&
cd $DIRECTORY > /dev/null &&
git commit -a -m 'lodash(_.capitalize) -> lodash(_.upperFirst)' > /dev/null &&
cd - > /dev/null

echo 'lodash(_.max) -> lodash(_.maxBy)'
(
  grasp --equery '_.max($object, $key)' --replace '_.maxBy({{object}}, {{key}})' \
    --in-place --only-matching --recursive $DIRECTORY ||
  echo "$(tput setaf 3)Bad stuff with lodash(_.max) -> lodash(_.maxBy)$(tput setaf 0)"
) &&
cd $DIRECTORY > /dev/null &&
git commit -a -m 'lodash(_.max) -> lodash(_.maxBy)' > /dev/null &&
cd - > /dev/null

echo 'lodash(_.min) -> lodash(_.minBy)'
(
  grasp --equery '_.min($object, $key)' --replace '_.minBy({{object}}, {{key}})' \
    --in-place --only-matching --recursive $DIRECTORY ||
  echo "$(tput setaf 3)Bad stuff with lodash(_.min) -> lodash(_.minBy)$(tput setaf 0)"
) &&
cd $DIRECTORY > /dev/null &&
git commit -a -m 'lodash(_.min) -> lodash(_.minBy)' > /dev/null &&
cd - > /dev/null
