#!/bin/sh
#
# $ ./underscore_to_lodash directory_with_js_to_refactor
#
# All JS is refactored: you must remove `node_modules` beforehand.
#

RULES_FOLDER="rules"
if [ ! -d $1 ] || [ -z $1 ]
then
  echo "$0 <folder with some js>"
  echo "\tWill run all transformations available in \`$RULES_FOLDER\`."
  case $1 in
    -h|--help)
      exit 0;;
    *)
      exit 1;;
  esac
fi

DIRECTORY=`readlink -f $1`
cd $(dirname $0)
for rule in $( find $RULES_FOLDER -type f | sort )
do
  if [ -x $rule ] && $rule $DIRECTORY
  then
    echo "o: $rule"
  else
    echo "x: $rule"
  fi
done

echo "$(tput setaf 1)"
echo "#                                   #"
echo "# Here are calls to handle MANUALLY #"
echo "#                                   #"
echo "$(tput setaf 0)"
grasp --only-matching --recursive --equery '_.chain(__)' $DIRECTORY
grasp --only-matching --recursive --equery '_(__)' $DIRECTORY

#
# Check if `grasp` missed some calls
#
for fn in $( cat blacklist )
do
  if grep --quiet --max-count=1 --recursive --exclude-dir=.git -e $fn $DIRECTORY
  then
    grep -rnH --color --exclude-dir=.git -e $fn $DIRECTORY
    exit 2
  fi
done

exit 0
