#!/bin/sh
#
# underscore(_.where) -> lodash(_.filter)
#
cd $1 &&
grasp --equery '_.where($list, $object)' \
    --replace '_.filter({{list}}, {{object}})' \
    --in-place --only-matching --recursive . > /dev/null &&
git commit -a -m 'underscore(_.where) -> lodash(_.filter)' > /dev/null
