#!/bin/sh
#
# airvantage(_.deep) -> lodash(_.get)
#
cd $1 &&
grasp --equery '_.deep($object, $path)' \
    --replace '_.get({{object}}, {{path}})' \
    --in-place --only-matching --recursive . > /dev/null &&
git commit -a -m 'airvantage(_.deep) -> lodash(_.get)' > /dev/null
