#!/bin/sh
#
# underscore(_.unique) -> lodash(_.uniqBy)
#
cd $1 &&
grasp --equery '_.unique($array, false, $fn)' \
    --replace '_.uniqBy({{array}}, {{fn}})' \
    --in-place --only-matching --recursive . > /dev/null &&
git commit -a -m 'underscore(_.unique) -> lodash(_.uniqBy)' > /dev/null
