#!/bin/sh
#
# underscore(_.unique) -> lodash(_.sortedUniqBy)
#
cd $1 &&
grasp --equery '_.unique($array, true, $fn)' \
    --replace '_.sortedUniqBy({{array}}, {{fn}})' \
    --in-place --only-matching --recursive . > /dev/null &&
git commit -a -m 'underscore(_.unique) -> lodash(_.sortedUniqBy)' > /dev/null
