#!/bin/sh
#
# underscore(_.uniq) -> lodash(_.uniqBy)
#
cd $1 &&
grasp --equery '_.uniq($array, false, $fn)' \
    --replace '_.uniqBy({{array}}, {{fn}})' \
    --in-place --only-matching --recursive . > /dev/null &&
git commit -a -m 'underscore(_.uniq) -> lodash(_.uniqBy)' > /dev/null
