#!/bin/sh
#
# underscore(_.uniq) -> lodash(_.sortedUniq)
#
cd $1 &&
grasp --equery '_.uniq($array, true)' \
    --replace '_.sortedUniq({{array}})' \
    --in-place --only-matching --recursive . > /dev/null &&
git commit -a -m 'underscore(_.uniq) -> lodash(_.sortedUniq)' > /dev/null
