#!/bin/sh
#
# underscore(_.uniq) -> lodash(_.sortedUniqBy)
#
grasp --equery '_.uniq($array, true, $fn)' \
    --replace '_.sortedUniqBy({{array}}, {{fn}})' \
    --in-place --only-matching --recursive . > /dev/null &&
git commit -a -m 'underscore(_.uniq) -> lodash(_.sortedUniqBy)' > /dev/null
