#!/bin/sh
#
# underscore(_.indexOf) -> lodash(_.sortedIndexOf)
#
grasp --equery '_.indexOf($array, $value, true)' \
    --replace '_.sortedIndexOf({{array}}, {{value}})' \
    --in-place --only-matching --recursive . > /dev/null &&
git commit -a -m 'underscore(_.indexOf) -> lodash(_.sortedIndexOf)' > /dev/null
