#!/bin/sh
#
# underscore(_.indexOf) -> lodash(_.indexOf)
#
grasp --equery '_.indexOf($array, $value, false)' \
    --replace '_.indexOf({{array}}, {{value}})' \
    --in-place --only-matching --recursive . > /dev/null &&
git commit -a -m 'underscore(_.indexOf) -> lodash(_.indexOf)' > /dev/null
