#!/bin/sh
#
# underscore(_.extend) -> lodash(_.assignIn)
#
cd $1 &&
grasp --equery '_.extend(_$objects)' \
    --replace '_.assignIn({{objects | join ", "}})' \
    --in-place --only-matching --recursive . > /dev/null &&
git commit -a -m 'underscore(_.extend) -> lodash(_.assignIn)' > /dev/null
