#!/bin/sh
#
# underscore(_.rest) -> lodash(_.drop)
#
grasp --equery '_.rest($array, $n)' \
    --replace '_.drop({{array}}, {{n}})' \
    --in-place --only-matching --recursive . > /dev/null &&
git commit -a -m 'underscore(_.rest) -> lodash(_.drop)' > /dev/null
