#!/bin/sh
#
# underscore(_.min) -> lodash(_.head(_.sortBy(_.bind))
#
cd $1 &&
grasp --equery '_.min($list, $fn, $context)' \
    --replace '_.head(_.sortBy({{list}}, _.bind({{fn}}, {{context}})))' \
    --in-place --only-matching --recursive . > /dev/null &&
git commit -a -m 'underscore(_.min) -> lodash(_.head(_.sortBy(_.bind))' > /dev/null
