#!/bin/sh
#
# underscore(_.first) -> lodash(_.head)
#
cd $1 &&
grasp --equery '_.first($array)' \
    --replace '_.head({{array}})' \
    --in-place --only-matching --recursive . > /dev/null &&
git commit -a -m 'underscore(_.first) -> lodash(_.head)' > /dev/null
