#!/bin/sh
#
# underscore(_.max) -> lodash(_.maxBy)
#
cd $1 &&
grasp --equery '_.max($list, $fn)' \
    --replace '_.maxBy({{list}}, {{fn}})' \
    --in-place --only-matching --recursive . > /dev/null &&
git commit -a -m 'underscore(_.max) -> lodash(_.maxBy)' > /dev/null
