#!/bin/sh
#
# underscore(_.max) -> lodash(_.maxBy(_.bind)
#
cd $1 &&
grasp --equery '_.max($list, $fn, $context)' \
    --replace '_.maxBy({{list}}, _.bind({{fn}}, {{context}}))' \
    --in-place --only-matching --recursive . > /dev/null &&
git commit -a -m 'underscore(_.max) -> lodash(_.maxBy(_.bind)' > /dev/null
