#!/bin/sh
#
# underscore(_.indexBy) -> lodash(_.bind(_.keyBy))
#
cd $1 &&
grasp --equery '_.indexBy($collection, $fn, $context)' \
    --replace '_.keyBy({{collection}}, _.bind({{fn}}, {{context}}))' \
    --in-place --only-matching --recursive . > /dev/null &&
git commit -a -m 'underscore(_.indexBy) -> lodash(_.bind(_.keyBy))' > /dev/null
