#!/bin/sh
#
# underscore(_.reject) -> lodash(_.bind(_.reject))
#
cd $1 &&
grasp --equery '_.reject($list, $fn, $context)' \
    --replace '_.reject({{list}}, _.bind({{fn}}, {{context}}))' \
    --in-place --only-matching --recursive . > /dev/null &&
git commit -a -m 'underscore(_.reject) -> lodash(_.bind(_.reject))' > /dev/null
