#!/bin/sh
#
# underscore(_.omit) -> lodash(_.omit)
#
cd $1 &&
grasp --equery '_.omit($object, _$keys)' \
    --replace '_.omit({{object}}, [{{keys | join ", "}}])' \
    --in-place --only-matching --recursive . > /dev/null &&
git commit -a -m 'underscore(_.omit) -> lodash(_.omit)' > /dev/null
